// fdvpd -- LVS reference for layout/build/fdvpd/fdvpd.gds,
// generated by top_netlist.py.  The analog cells come from their
// *_ref.spice netlists, fdvpd_ctrl from LibreLane's powered netlist.
module fdvpd (vdd, vss, rst_n, ref_clk, ckv, ckvd, code_valid, railed, fcw_int, fcw_frac, trim_in, code, count_ref);
    inout vdd, vss;
    input rst_n;
    input ref_clk;
    input ckv;
    output ckvd;
    output code_valid;
    output railed;
    input [7:0] fcw_int;
    input [15:0] fcw_frac;
    input [6:0] trim_in;
    output [6:0] code;
    output [7:0] count_ref;
    wire outp;
    wire outn;
    wire vp;
    wire vn;
    wire rs;
    wire vg;
    wire nbias;
    wire rcbias;
    wire ibias;
    wire dcbias;
    wire s1_n;
    wire s2_n;
    wire cmp_clk;
    wire cmp_p;
    wire cmp_n;
    wire vrp20;
    wire vrp10;
    wire vrp5;
    wire vrm;
    wire vrn5;
    wire vrn10;
    wire vrn20;
    wire [20:0] dsw;
    wire [20:0] dswb;
    wire [6:0] trim;
    wire [5:0] bpos;
    wire [5:0] bneg;
    wire [5:0] bmid;

    fdvpd_ctrl u_ctl (
        .VPWR(vdd),
        .VGND(vss),
        .rst_n(rst_n),
        .ref_clk(ref_clk),
        .ckv(ckv),
        .fcw_int(fcw_int),
        .fcw_frac(fcw_frac),
        .trim_in(trim_in),
        .cmp_p(cmp_p),
        .cmp_n(cmp_n),
        .ckvd(ckvd),
        .dsw(dsw),
        .dswb(dswb),
        .trim(trim),
        .s1_n(s1_n),
        .s2_n(s2_n),
        .cmp_clk(cmp_clk),
        .bpos(bpos),
        .bneg(bneg),
        .bmid(bmid),
        .code(code),
        .code_valid(code_valid),
        .railed(railed),
        .count_ref(count_ref));

    idac u_dac (
        .vdd(vdd),
        .vss(vss),
        .ibias(ibias),
        .cbias(dcbias),
        .outp(outp),
        .outn(outn),
        .d_t0(dsw[0]),
        .db_t0(dswb[0]),
        .d_t1(dsw[1]),
        .db_t1(dswb[1]),
        .d_t2(dsw[2]),
        .db_t2(dswb[2]),
        .d_t3(dsw[3]),
        .db_t3(dswb[3]),
        .d_t4(dsw[4]),
        .db_t4(dswb[4]),
        .d_t5(dsw[5]),
        .db_t5(dswb[5]),
        .d_t6(dsw[6]),
        .db_t6(dswb[6]),
        .d_t7(dsw[7]),
        .db_t7(dswb[7]),
        .d_t8(dsw[8]),
        .db_t8(dswb[8]),
        .d_t9(dsw[9]),
        .db_t9(dswb[9]),
        .d_t10(dsw[10]),
        .db_t10(dswb[10]),
        .d_t11(dsw[11]),
        .db_t11(dswb[11]),
        .d_t12(dsw[12]),
        .db_t12(dswb[12]),
        .d_t13(dsw[13]),
        .db_t13(dswb[13]),
        .d_t14(dsw[14]),
        .db_t14(dswb[14]),
        .d_b5(dsw[15]),
        .db_b5(dswb[15]),
        .d_b4(dsw[16]),
        .db_b4(dswb[16]),
        .d_b3(dsw[17]),
        .db_b3(dswb[17]),
        .d_b2(dsw[18]),
        .db_b2(dswb[18]),
        .d_b1(dsw[19]),
        .db_b1(dswb[19]),
        .d_b0(dsw[20]),
        .db_b0(dswb[20]),
        .trim0(trim[0]),
        .trim1(trim[1]),
        .trim2(trim[2]),
        .trim3(trim[3]),
        .trim4(trim[4]),
        .trim5(trim[5]),
        .trim6(trim[6]));

    ramp_sink u_ramp (
        .vss(vss),
        .outp(rs),
        .nbias(nbias),
        .cbias(rcbias));

    sarfe u_fe (
        .vdd(vdd),
        .vss(vss),
        .outp(outp),
        .outn(outn),
        .rs(rs),
        .vg(vg),
        .s1_n(s1_n),
        .s2_n(s2_n),
        .cmp_clk(cmp_clk),
        .cmp_p(cmp_p),
        .cmp_n(cmp_n),
        .vp(vp),
        .vn(vn),
        .bpos0(bpos[0]),
        .bpos1(bpos[1]),
        .bpos2(bpos[2]),
        .bpos3(bpos[3]),
        .bpos4(bpos[4]),
        .bpos5(bpos[5]),
        .bneg0(bneg[0]),
        .bneg1(bneg[1]),
        .bneg2(bneg[2]),
        .bneg3(bneg[3]),
        .bneg4(bneg[4]),
        .bneg5(bneg[5]),
        .bmid0(bmid[0]),
        .bmid1(bmid[1]),
        .bmid2(bmid[2]),
        .bmid3(bmid[3]),
        .bmid4(bmid[4]),
        .bmid5(bmid[5]),
        .vrp20(vrp20),
        .vrp10(vrp10),
        .vrp5(vrp5),
        .vrm(vrm),
        .vrn5(vrn5),
        .vrn10(vrn10),
        .vrn20(vrn20));

    bias u_bias (
        .vdd(vdd),
        .vss(vss),
        .iramp(nbias),
        .icbr(rcbias),
        .idac(ibias),
        .dcbias(dcbias),
        .vrp20(vrp20),
        .vrp10(vrp10),
        .vrp5(vrp5),
        .vrm(vrm),
        .vrn5(vrn5),
        .vrn10(vrn10),
        .vrn20(vrn20),
        .isw(vg));

endmodule
