#!/usr/bin/env python3
"""FDVPD top level -- generate the LVS reference ``fdvpd_ref.v``.

Structural Verilog, because the control macro's reference is LibreLane's
powered netlist (Verilog, bus ports): named connections to it cannot get the
bit order wrong, and netgen reads the analog cells' SPICE subcircuits into the
same netlist and resolves the Verilog instances against them by pin name.

    python3 top_netlist.py        # writes fdvpd_ref.v

The connections are the detector's, written out once here; top.py draws them
and LVS compares the two.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "..", "digital"))
import fe_netlist as fe  # noqa: E402
import idac_netlist as dac  # noqa: E402
import pins_def  # noqa: E402

TAPS = ["vrp20", "vrp10", "vrp5", "vrm", "vrn5", "vrn10", "vrn20"]
#: the detector's own pins, and their widths: the macro's south edge
BUSES = {"fcw_int": 8, "fcw_frac": 16, "trim_in": 7, "code": 7, "count_ref": 8}
INPUTS = {"rst_n", "ref_clk", "ckv", "fcw_int", "fcw_frac", "trim_in"}


def conn(pairs):
    return ",\n        ".join(f".{p}({n})" for p, n in pairs)


def netlist():
    seg_of = {s: k for k, s in pins_def.SEG.items()}
    scalars = ["rst_n", "ref_clk", "ckv", "ckvd", "code_valid", "railed"]
    ports = ["vdd", "vss"] + scalars + list(BUSES)
    L = ["// fdvpd -- LVS reference for layout/build/fdvpd/fdvpd.gds,",
         "// generated by top_netlist.py.  The analog cells come from their",
         "// *_ref.spice netlists, fdvpd_ctrl from LibreLane's powered netlist.",
         f"module fdvpd ({', '.join(ports)});",
         "    inout vdd, vss;"]
    for p in scalars:
        L.append(f"    {'input' if p in INPUTS else 'output'} {p};")
    for p, w in BUSES.items():
        L.append(f"    {'input' if p in INPUTS else 'output'} [{w - 1}:0] {p};")
    # one bus per declaration: netgen's Verilog reader gives the range to the
    # first name only, and "wire [20:0] dsw, dswb;" left dswb a single net
    L += [f"    wire {n};" for n in (
        "outp", "outn", "vp", "vn", "rs", "vg", "nbias", "rcbias", "ibias",
        "dcbias", "s1_n", "s2_n", "cmp_clk", "cmp_p", "cmp_n", *TAPS)]
    L += ["    wire [20:0] dsw;", "    wire [20:0] dswb;", "    wire [6:0] trim;",
          "    wire [5:0] bpos;", "    wire [5:0] bneg;", "    wire [5:0] bmid;", ""]

    ctl = [("VPWR", "vdd"), ("VGND", "vss")] + [(p, p) for p in (
        "rst_n", "ref_clk", "ckv", "fcw_int", "fcw_frac", "trim_in", "cmp_p",
        "cmp_n", "ckvd", "dsw", "dswb", "trim", "s1_n", "s2_n", "cmp_clk",
        "bpos", "bneg", "bmid", "code", "code_valid", "railed", "count_ref")]
    L += [f"    fdvpd_ctrl u_ctl (\n        {conn(ctl)});", ""]

    d = []
    for p in dac.ports():
        if p in ("vdd", "vss", "outp", "outn"):
            d.append((p, p))
        elif p == "ibias":
            d.append((p, "ibias"))
        elif p == "cbias":
            d.append((p, "dcbias"))
        elif p.startswith("trim"):
            d.append((p, f"trim[{p[4:]}]"))
        elif p.startswith("d_"):
            d.append((p, f"dsw[{seg_of[p[2:]]}]"))
        elif p.startswith("db_"):
            d.append((p, f"dswb[{seg_of[p[3:]]}]"))
        else:
            raise ValueError(p)
    L += [f"    idac u_dac (\n        {conn(d)});", ""]

    r = [("vss", "vss"), ("outp", "rs"), ("nbias", "nbias"), ("cbias", "rcbias")]
    L += [f"    ramp_sink u_ramp (\n        {conn(r)});", ""]

    f = []
    for p in fe.ports():
        base = p.rstrip("0123456789")
        if base in ("bpos", "bneg", "bmid"):
            f.append((p, f"{base}[{p[len(base):]}]"))
        else:
            f.append((p, p))
    L += [f"    sarfe u_fe (\n        {conn(f)});", ""]

    b = [("vdd", "vdd"), ("vss", "vss"), ("iramp", "nbias"), ("icbr", "rcbias"),
         ("idac", "ibias"), ("dcbias", "dcbias")] + [(t, t) for t in TAPS] + \
        [("isw", "vg")]
    L += [f"    bias u_bias (\n        {conn(b)});", "", "endmodule", ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("-o", default=os.path.join(HERE, "fdvpd_ref.v"))
    args = ap.parse_args()
    with open(args.o, "w", newline="\n") as fh:
        fh.write(netlist())
    print(f"wrote {os.path.basename(args.o)}")


if __name__ == "__main__":
    main()
